---
- name: Install multiple packages
  apt:
    name:
      - vim
      - telnet
      - net-tools
      - iputils-ping
    state: present
    update_cache: yes

- block:
  - name : Install required packages
    package:
      name :
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state : present

  - name : Add Docker GPG key
    apt_key:
      url : https://download.docker.com/linux/debian/gpg
      state : present
    environment :
      http_proxy : 'http://fra1-proxy1-pr:3128'
      https_proxy : 'http://fra1-proxy1-pr:3128'


  - name : Add Docker repository
    apt_repository :
      repo : "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state : present

  - name : Update the apt package index
    apt :
      update_cache : yes

  - name : Install Docker
    package :
      name : docker-ce
      state : present

  - name : Install Docker Python module
    pip :
      name : docker
      state : present

  - name : Start and enable Docker service
    service :
      name : docker
      state : started
      enabled : yes
  when:
    - inventory_hostname in groups['docker_plugin']