---
- name: Create nomad data dir
  become: true
  file:
    path: /{{ nomad_data_dir }}
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy nomad server config
  become: true
  copy:
    src: server.hcl
    dest: /etc/nomad.d/nomad.hcl
    mode: '644'
  when: inventory_hostname in groups['nomad_servers']
  notify:
    - Restart nomad

- name: Copy nomad client config
  become: true
  template:
    src: client.j2
    dest: /etc/nomad.d/nomad.hcl
    mode: '644'
  when: inventory_hostname in groups['nomad_clients']
  notify:
    - Restart nomad